### ISSUE TITLE
[BUG] config file "weaver.toml": section "gke" has unknown keys [project]

### ISSUE THREAD

**Issue by rwrz** [ServiceWeaver/weaver-gke#117]
The documentation explains that I can set up the default project's on my `weaver.toml` file.
But as soon I add it to the gke section, It stops accepting my config file. 

`weaver gke v0.22.2 linux/amd64`
`weaver v0.22.0 linux/amd64`

```toml
[serviceweaver]
binary = "./anything"

[gke]
project = "something-123"
```
